# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

workspace 'File Upload Sample WS'

target 'File Upload Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for File Upload Sample
  pod 'AzureIoTUtility', '1.0.0-pre-release-1.0.0'
  #pod 'AzureIoTuMqtt', '1.0.0-pre-release-1.0.0'
  pod 'AzureIoTuAmqp', '1.0.0-pre-release-1.0.0'
  pod 'AzureIoTHubClient', '1.0.0-pre-release-1.0.0'
end
